cse136_hw4/MVC3/Controllers/ProductVariationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC3.Models;

namespace MVC3.Controllers
{
    public class ProductVariationController : Controller
    {
        ProductVariationList pvList = new ProductVariationList();

        public ActionResult Create()
        {
            AllProductInfo api = new AllProductInfo();
            return View("Create", api);
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                PLProductVariation plpv = new PLProductVariation();
                plpv.pv_id = 10;
                plpv.product_id = int.Parse(collection["product_id"]);
                plpv.brand_id = int.Parse(collection["brand_id"]);
                plpv.product_color_id = int.Parse(collection["color_id"]);
                plpv.product_cutting_id = int.Parse(collection["cutting_id"]);
                plpv.product_type_id = int.Parse(collection["type_id"]);
                plpv.sex = char.Parse(collection["sex"]);
                plpv.size = collection["size"];
                plpv.stock = int.Parse(collection["stock"]);
                plpv.price = float.Parse(collection["price"]);
                plpv.condition = char.Parse(collection["condition"]);

                ProductVariationClientService.CreateProductVariation(plpv);

                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View();
            }
        }

        //
        // GET: /ProductVariation/

        public ActionResult Index()
        {
            List<PLProductVariation> plpv = new List<PLProductVariation>();

            List<SLProductVariation.ProductVariationInfo> pvList = this.pvList.GetPVList('z');

            for (int i = 0; i < pvList.Count; i++)
            {
                plpv.Add(ProductVariationClientService.DTO_to_PL(pvList[i]));
            }

            AllProductInfo api = new AllProductInfo();
            api.pvList = plpv;
            return View("Index", api);
        }

        public ActionResult Details(int id)
        {
            SLProductVariation.ProductVariationInfo pv = this.pvList.GetPVDetail(id - 1);

            PLProductVariation plpv = ProductVariationClientService.DTO_to_PL(pv);

            return View("Details", plpv);
        }

        public ActionResult Edit(int id)
        {
            SLProductVariation.ProductVariationInfo pv = this.pvList.GetPVDetail(id);

            PLProductVariation plpv = ProductVariationClientService.DTO_to_PL(pv);

            AllProductInfo api = new AllProductInfo();

            api.pvList[0] = plpv;

            return View("Edit", api);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            try
            {
                PLProductVariation plpv = new PLProductVariation();
                plpv.pv_id = int.Parse(collection["pv_id"]);
                plpv.product_id = int.Parse(collection["products"]);
                plpv.brand_id = int.Parse(collection["brands"]);
                plpv.product_color_id = int.Parse(collection["colors"]);
                plpv.product_cutting_id = int.Parse(collection["cuttings"]);
                plpv.product_type_id = int.Parse(collection["types"]);
                plpv.sex = char.Parse(collection["sexes"]);
                plpv.size = collection["sizes"];
                plpv.stock = int.Parse(collection["stocks"]);
                plpv.price = float.Parse(collection["prices"]);
                plpv.condition = char.Parse(collection["condition"]);

                ProductVariationClientService.UpdateProductVariation(plpv);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine("HERE IS THE ERROR: " + e.ToString());
                AllProductInfo api = new AllProductInfo();
                return View("Index", api);
            }
        }

        public ActionResult Delete(int id)
        {
            SLProductVariation.SLProductVariationClient slpv = new SLProductVariation.SLProductVariationClient();
            string[] errors = new string[0];
            slpv.DeletePV(id, ref errors);
            AllProductInfo api = new AllProductInfo();
            //api.pvList[id] = ProductVariationClientService.ReadProductVariationDetail(id);
            return View("Index", api);
        }

        public ActionResult GetAll()
        {
            List<PLProductVariation> plpv = new List<PLProductVariation>();

            List<SLProductVariation.ProductVariationInfo> pvList = this.pvList.GetPVList('z');

            for (int i = 0; i < pvList.Count; i++)
            {
                plpv.Add(ProductVariationClientService.DTO_to_PL(pvList[i]));
            }

            AllProductInfo api = new AllProductInfo();
            api.pvList = plpv;
            return View("Index", api);
        }

        public ActionResult GetAvailable()
        {
            List<PLProductVariation> plpv = new List<PLProductVariation>();

            List<SLProductVariation.ProductVariationInfo> pvList = this.pvList.GetPVList('a');

            AllProductInfo api = new AllProductInfo();

            for (int i = 0; i < pvList.Count; i++)
            {
                plpv.Add(ProductVariationClientService.DTO_to_PL(pvList[i]));
            }

            api.pvList = plpv;

            return View("Index", api);
        }

        public ActionResult GetDeleted()
        {
            List<PLProductVariation> plpv = new List<PLProductVariation>();

            List<SLProductVariation.ProductVariationInfo> pvList = this.pvList.GetPVList('d');

            AllProductInfo api = new AllProductInfo();

            for (int i = 0; i < pvList.Count; i++)
            {
                plpv.Add(ProductVariationClientService.DTO_to_PL(pvList[i]));
            }

            api.pvList = plpv;

            return View("Index", api);
        }
    }
}

cse136_hw4/MVC3/Views/ProductVariation/Create.cshtml
@model MVC3.Models.AllProductInfo
           
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "ProductVariation", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Product Variation</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.productList[0].Product_id)
        </div>
        <div class="editor-field">
            <select name="products">
            @for(int i = 0; i < Model.productList.Count; i++)
            {
                <option value="@i.ToString()">@Model.productList[i].product_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.brandList[0].Brand_id)
        </div>
        <div class="editor-field">
            <select name="brands">
            @for (int i = 0; i < Model.brandList.Count; i++)
            {
                <option value=@i.ToString()>@Model.brandList[i].Brand_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.colorList[0].ProductColor_id)
        </div>
        <div class="editor-field">
            <select name="colors">
            @for (int i = 0; i < Model.colorList.Count; i++)
            {
                <option value=@i.ToString()>@Model.colorList[i].ProductColor_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].product_cutting_id)
        </div>
        <div class="editor-field">
            <select name="cuttings">
            @for (int i = 0; i < Model.cuttingList.Count; i++)
            {
                <option value=@i.ToString()>@Model.cuttingList[i].ProductCutting_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].product_type_id)
        </div>
        <div class="editor-field">
            <select name="types">
            @for (int i = 0; i < Model.typeList.Count; i++)
            {
                <option value=@i.ToString()>@Model.typeList[i].ProductType_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].sex)
        </div>
        <div class="editor-field">
            <select name="sexes">
                <option value="M">Male</option>
                <option value="F">Female</option>
                <option value="U">Undefined</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].size)
        </div>
        <div class="editor-field">
            <select name="sizes">
                <option value="XS">XS</option>
                <option value="S">S</option>
                <option value="M">M</option>
                <option value="L">L</option>
                <option value="XL">XL</option>
                <option value="XXL">XXL</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].stock)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pvList[0].stock)
            @Html.ValidationMessageFor(model => model.pvList[0].stock)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pvList[0].price)
            @Html.ValidationMessageFor(model => model.pvList[0].price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].condition)
        </div>
        <div class="editor-field">
            <select name="conditions">
                <option value="a">Available</option>
                <option value="d">Delete</option>
            </select>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    var product_id = "@Html.DisplayFor(model => model.pvList[0].product_id)";
    var brand_id = "@Html.DisplayFor(model => model.pvList[0].brand_id)";
    var product_color_id = "@Html.DisplayFor(model => model.pvList[0].product_color_id)";
    var product_cutting_id = "@Html.DisplayFor(model => model.pvList[0].product_cutting_id)";
    var product_type_id = "@Html.DisplayFor(model => model.pvList[0].product_type_id)";
    var sex = "@Html.DisplayFor(model => model.pvList[0].sex)";
    var size = "@Html.DisplayFor(model => model.pvList[0].size)";
    var stock = "@Html.DisplayFor(model => model.pvList[0].stock)";
    var price = "@Html.DisplayFor(model => model.pvList[0].price)";
    var condition = "@Html.DisplayFor(model => model.pvList[0].condition)";

    $(document).ready(function () {
        $("select[name=products] option[value=" + product_id + "]").attr("selected", "selected");
        $("select[name=brands] option[value=" + brand_id + "]").attr("selected", "selected");
        $("select[name=colors] option[value=" + product_color_id + "]").attr("selected", "selected");
        $("select[name=cutting] option[value=" + product_cutting_id + "]").attr("selected", "selected");
        $("select[name=types] option[value=" + product_type_id + "]").attr("selected", "selected");
        $("select[name=sexes] option[value=" + sex + "]").attr("selected", "selected");
        $("select[name=sizes] option[value=" + size + "]").attr("selected", "selected");
        //$("select[name=products] option[value=" + product_variation_id + "]").attr("selected", "selected");
        //$("select[name=products] option[value=" + product_variation_id + "]").attr("selected", "selected");
        $("select[name=conditions] option[value=" + condition + "]").attr("selected", "selected");
    });
</script>

cse136_hw4/MVC3/Views/ProductVariation/Details.cshtml
@model MVC3.Models.PLProductVariation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ProductVariationInfo</legend>

    <div class="display-label">product_variation_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pv_id)
    </div>

    <div class="display-label">product_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.product_id)
    </div>

    <div class="display-label">product_brand_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.brand_id)
    </div>

    <div class="display-label">product_cutting_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.product_cutting_id)
    </div>

    <div class="display-label">product_color_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.product_color_id)
    </div>

    <div class="display-label">product_type_id</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.product_type_id)
    </div>

    <div class="display-label">sex</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.sex)
    </div>

    <div class="display-label">size</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.size)
    </div>

    <div class="display-label">stock</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.stock)
    </div>

    <div class="display-label">price</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.price)
    </div>

    <div class="display-label">condition</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.condition)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.pv_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

cse136_hw4/MVC3/Views/ProductVariation/Edit.cshtml
@model MVC3.Models.AllProductInfo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "ProductVariation", FormMethod.Post)) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Product Variation</legend>

            <input type="hidden" name="pv_id" value="@Model.pvList[0].pv_id)" />
            <label>PV ID</label>
            <label> @Model.pvList[0].pv_id </label>

        <div class="editor-label">
            @Html.LabelFor(model => model.productList[0].Product_id)
        </div>
        <div class="editor-field" id="products">
            <select name="products">
            @for (int i = 0; i < Model.productList.Count; i++)
            {
                <option value="@i.ToString()">@Model.productList[i].product_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.brandList[0].Brand_id)
        </div>
        <div class="editor-field" id="brands">
            <select name="brands">
            @for (int i = 0; i < Model.brandList.Count; i++)
            {
                <option value="@i.ToString()">@Model.brandList[i].Brand_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.colorList[0].ProductColor_id)
        </div>
        <div class="editor-field" id="colors">
            <select name="colors">
            @for (int i = 0; i < Model.colorList.Count; i++)
            {
                <option value="@i.ToString()">@Model.colorList[i].ProductColor_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].product_cutting_id)
        </div>
        <div class="editor-field" id="cuttings">
            <select name="cuttings">
            @for (int i = 0; i < Model.cuttingList.Count; i++)
            {
                <option value="@i.ToString()">@Model.cuttingList[i].ProductCutting_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].product_type_id)
        </div>
        <div class="editor-field" id="types">
            <select name="types">
            @for (int i = 0; i < Model.typeList.Count; i++)
            {
                <option value="@i.ToString()">@Model.typeList[i].ProductType_name</option>
            }
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].sex)
        </div>
        <div class="editor-field" id="sexes">
            <select name="sexes">
                <option value="M">Male</option>
                <option value="F">Female</option>
                <option value="U">Undefined</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].size)
        </div>
        <div class="editor-field" id="sizes">
            <select name="sizes">
                <option value="XS">XS</option>
                <option value="S">S</option>
                <option value="M">M</option>
                <option value="L">L</option>
                <option value="XL">XL</option>
                <option value="XXL">XXL</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].stock)
        </div>
        <div class="editor-field" id="stocks">
            @Html.EditorFor(model => model.pvList[0].stock)
            @Html.ValidationMessageFor(model => model.pvList[0].stock)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].price)
        </div>
        <div class="editor-field" id="prices">
            @Html.EditorFor(model => model.pvList[0].price)
            @Html.ValidationMessageFor(model => model.pvList[0].price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pvList[0].condition)
        </div>
        <div class="editor-field" id="conditions">
            <select name="conditions">
                <option value="a">Available</option>
                <option value="d">Delete</option>
            </select>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<!--<script>
    var product_variation_id = "@Html.DisplayFor(model => model.pvList[0].pv_id)";
    var product_id = "@Html.DisplayFor(model => model.pvList[0].product_id)";
    var brand_id = "@Html.DisplayFor(model => model.pvList[0].brand_id)";
    var product_color_id = "@Html.DisplayFor(model => model.pvList[0].product_color_id)";
    var product_cutting_id = "@Html.DisplayFor(model => model.pvList[0].product_cutting_id)";
    var product_type_id = "@Html.DisplayFor(model => model.pvList[0].product_type_id)";
    var sex = "@Html.DisplayFor(model => model.pvList[0].sex)";
    var size = "@Html.DisplayFor(model => model.pvList[0].size)";
    var stock = "@Html.DisplayFor(model => model.pvList[0].stock)";
    var price = "@Html.DisplayFor(model => model.pvList[0].price)";
    var condition = "@Html.DisplayFor(model => model.pvList[0].condition)";

    $(document).ready(function () {
        $("select[name=products] option[value=" + product_id + "]").attr("selected", "selected");
        $("select[name=brands] option[value=" + brand_id + "]").attr("selected", "selected");
        $("select[name=colors] option[value=" + product_color_id + "]").attr("selected", "selected");
        $("select[name=cutting] option[value=" + product_cutting_id + "]").attr("selected", "selected");
        $("select[name=types] option[value=" + product_type_id + "]").attr("selected", "selected");
        $("select[name=sexes] option[value=" + sex + "]").attr("selected", "selected");
        $("select[name=sizes] option[value=" + size + "]").attr("selected", "selected");
        //$("select[name=products] option[value=" + product_variation_id + "]").attr("selected", "selected");
        //$("select[name=products] option[value=" + product_variation_id + "]").attr("selected", "selected");
        $("select[name=conditions] option[value=" + condition + "]").attr("selected", "selected");
    });
</script>-->

cse136_hw4/MVC3/Views/ProductVariation/Index.cshtml
@model MVC3.Models.AllProductInfo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
@Html.ActionLink("Get All", "GetAll", "ProductVariation")
</p>
<p>
@Html.ActionLink("Get Available", "GetAvailable", "ProductVariation")
</p>
<p>
@Html.ActionLink("Get Deleted", "GetDeleted", "ProductVariation")
</p>
 
<p>
    @Html.ActionLink("Create New", "Create", "ProductVariation")
</p>
<table>
    <tr>
        <th>
            product_variation_id
        </th>
        <th>
            product_id
        </th>
        <th>
            product_name
        </th>
        <th>
            product_brand_id
        </th>
        <th>
            product_brand_name
        </th>
        <th>
            product_cutting_id
        </th>
        <th>
            product_cutting_name
        </th>
        <th>
            product_color_id
        </th>
        <th>
            product_color_name
        </th>
        <th>
            product_type_id
        </th>
        <th>
            product_type_name
        </th>
        <th>
            sex
        </th>
        <th>
            size
        </th>
        <th>
            stock
        </th>
        <th>
            price
        </th>
        <th>
            condition
        </th>
        <th></th>
    </tr>

@for(int i = 0; i < Model.pvList.Count; i++) {//foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].pv_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].product_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.productList[Model.pvList[i].product_id].product_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].brand_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.brandList[Model.pvList[i].brand_id].Brand_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].product_cutting_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.cuttingList[Model.pvList[i].product_cutting_id].ProductCutting_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].product_color_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.colorList[Model.pvList[i].product_color_id].ProductColor_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].product_type_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.typeList[Model.pvList[i].product_type_id].ProductType_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].sex)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].stock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.pvList[i].condition)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = Model.pvList[i].pv_id }) |
            @Html.ActionLink("Details", "Details", new { id = Model.pvList[i].pv_id }) |
            @Html.ActionLink("Delete", "Delete", new { id = Model.pvList[i].pv_id })
        </td>
    </tr>
}

</table>